### ISSUE TITLE
Combine three buckets into one network

### ISSUE THREAD

**Issue by ronnie45596** [ronnie45596/deep_bucket_lab#1]

**Comment by jameshalgren** [comment]
Hi @ronnie45596 
Here's an idea for how you might select three random buckets from the bucket list to create a collection for the network:
```
def setup_networks(n_networks, buckets_per_network):
    networks = []
    for i in range(n_networks):
        networks.append([np.random.randint(0, n_buckets) for _ in range(buckets_per_network)])
    return networks

n_networks = 15
buckets_per_network = 3
networks = setup_networks(n_networks, buckets_per_network)
```

You can look at the parameters in the buckets with something like this:
```
for i, n in enumerate(networks):
    print(f"network {i}: buckets{n}")
    for k in buckets.keys():
        print(f"{k}:{[buckets[k][n[b]] for b in range(buckets_per_network)]}") 
```

**Comment by ronnie45596** [comment]
Thanks @jameshalgren 
Ping @rohansunkarapalli, this might be useful

**Comment by ronnie45596** [comment]
Hi @ronnie45596 
The next step is probably to create a dummy function to put all the flows together. 

It could get really complex, but for now, you can probably hand it a few inputs based on the assumption that you have a 3-network system. Something like this: 
```
def t_outflow(flows=None, transform_params=None):
    """
    flows: list of inflows for specific tilmestep, e.g., `[Q1, Q2, Q3]`
    transform_params: list of tuples containing transform parameters corresponding to list of inflows
    """
    transformed_flows = []
    for Q, T in zip(flows, transform_params):
        transformed_flows.append(transformQ(Q, T)
    return sum(transformed_flows)
```

We might actually want to return a series of transformed flows from this function, then do the sum in another function...

**Comment by jameshalgren** [comment]
Ping @aarm1978

**Comment by jameshalgren** [comment]
Per earlier discussion, this transform function could be stubbed with a null transform. The transform parameters in that case could be a single element tuple with 0 or None as the contained value. The transform would return the same series of flows given as input. 

```
def transform_Q(inputQseries, type=0, trunc=False, pad=True, **params=None):
    if type==0:
        return inputQseries
    if type==1:
        # read the params, do things with the Qseries, return the transformed series
        # pad the series with zeros or truncate to the input series length according to the trunc and pad inputs
        # more complex padding or truncating rules might be included in the params instead. 
etc.
```


Additional transforms of increasing complexity could be specified such as
* simple shift (move the elements right or left); 
* time-based shift (shift right or left based on number of seconds specified; requires some information about the internal time values of the series.)

Other transforms might include
* Simple Attenuation
* LagK
* Muskingum-Cunge

We can complete all objectives of this initial project with just the null transform.

**Comment by aarm1978** [comment]
Thanks @jameshalgren
If I am understanding correctly. The transform function with null transform could be something like this:

`
def transformQ(Q, T):
    # Verify if the transformation parameters are null

    if T[0] == 0 or T[0] is None:
        # The null transformation returns the same series of input streamflows
        return Q

    else:
        transform_type = T[0]

        if transform_type == 1:
            # Implement the simple shift transformation
            # Move the elements to the right or left according to parameters
            shift_amount = T[1]
            transformed_Q = Q[shift_amount:] + Q[:shift_amount]

        elif transform_type == 2:
            # Implementing time-based displacement transformation
            # Move the elements to the right or left according to the specified number of seconds
            time_shift = T[1]
            # Information about the internal time values of the series should be used here
            # to calculate the appropriate displacement based on the specified seconds
            # transformed_Q = ...
            # Implement the code for this transformation according to needs and available data

        elif transform_type == 3:
            # Implement the simple attenuation transformation
            # Multiplying each element of the series by an attenuation factor
            attenuation_factor = T[1]
            transformed_Q = [q * attenuation_factor for q in Q]

        elif transform_type == 4:
            # Implement LagK transformation
            # Move each element to position K
            lag_amount = T[1]
            transformed_Q = [Q[i - lag_amount] if i >= lag_amount else None for i in range(len(Q))]

        elif transform_type == 5:
            # Implement the Muskingum-Cunge method to combine river flows
            # transformed_Q = ...
            # Implement the code for this transformation according to needs and available data

        else:
            # In case new transformations are added in the future, they can be handled here by adding more elif blocks

        return transformed_Q
`

**Comment by aarm1978** [comment]
For some reason I can't get this part into the code spinet of my previous comment: 
`
def transformQ(Q, T):
     # Verify if the transformation parameters are null
`

**Comment by ronnie45596** [comment]
@jameshalgren here is something that Andres and I came up with:
```
def run_basin_network_simultation():
    result = {}
    result['buckets'] = {}
    for i in range(n_basin_networks):
        bucket_dictionary = {}
        for j in range(n_buckets_per_network):
            bucket_dictionary[j] = run_bucket_simulation((i * n_buckets_per_network) + j)
        result['buckets'][i] = bucket_dictionary
    return result
```
This function creates a dictionary within a dictionary. It also creates the network with three buckets. Where you see run_bucket_simulation((i*n_buckets_per_network)+j), this where we created the different networks. 
```
basin_network_dictionary = {}
basin_network_dictionary = run_basin_network_simultation()
#print(basin_network_dictionary)
```
The one above displays the output of the buckets. For instance if we wanted three networks, the networks would be 0-3 and the buckets within the network would be 0-2 with the parameters of Jonathan's bucket.

**Comment by ronnie45596** [comment]
This function will create separate datasets for training, validation, and testing. 
```
def basin_split_param():
    #create lists of basin indices for each set
    basins_train = list(range(0, n_basin_networks_split['train']))
    basins_val = list(range(n_basin_networks_split['train'], 
                            n_basin_networks_split['train'] + n_basin_networks_split['val']))
    basins_test = list(range(n_basin_networks - n_basin_networks_split['test'], n_basin_networks)) 
    
    #place basin split parameters into separate lists
    train_basin_split_param = [basins_train]
    val_basin_split_param = [basins_val]
    test_basin_split_param = [basins_test]
    
    return [train_basin_split_param, val_basin_split_param, test_basin_split_param]
```
This will run the function above and print out the range for the whole basin split from 0-23
```
[[basins_train],[basins_val],[basins_test]]= basin_split_param()
print(basin_split_param())
```

**Comment by jameshalgren** [comment]
Excellent progress!

**Comment by aarm1978** [comment]
I just pushed an update to the GitHub repository. The update includes the following additions and changes:

1. Functions to create a bucket network with a customizable number of buckets in the network.
2. A function that implements four different types of transformations.
3. A function that combines the transformed q_overflow and q_spigots of the buckets in every basin network.
4. Updated descriptions for the functions in the Jupyter Notebook.

Next, I will explore how to integrate the function that Rohan made, which implements the Muskingum-Cunge transformation.

With these changes, we now have training, validation, and testing datasets for networks that contain three buckets each. These datasets include the combined out streamflows. It's important to verify the parameter ranges for both the buckets and the transformation functions to ensure the creation of reasonable synthetic data. Our next step is to explore how to construct the LSTM model for training.

Please feel free to review the updates and provide any feedback or suggestions.
